POST http://localhost:7482/jr/emitters
Content-Type: application/json

{
      "name": "net_device",
      "locale": "us",
      "num": 5,
      "preload": 0,
      "valueTemplate": "net_device",
      "output": "http",
      "keyTemplate": "null",
      "outputTemplate": "{{.V}}\n"
}

###
GET http://localhost:7482/jr/emitters

###

GET http://localhost:7482/jr/emitter/shoe

###

GET http://localhost:7482/jr/emitter/shoe_customer

###

GET http://localhost:7482/jr/emitter/shoe_order

###

GET http://localhost:7482/jr/emitter/shoe_clickstream

###

GET http://localhost:7482/jr/emitter/net_device

###

GET http://localhost:7482/jr/emitter/user