// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     campaign_finance.avsc
 *     click_stream.avsc
 *     click_stream_users.avsc
 *     clickstreamcodes.avsc
 *     credit_cards.avsc
 *     device_information.avsc
 *     fleet_mgmt_description.avsc
 *     fleet_mgmt_location.avsc
 *     fleet_mgmt_sensors.avsc
 *     gaming_games.avsc
 *     gaming_player_activity.avsc
 *     gaming_players.avsc
 *     insurance_customer_activity.avsc
 *     insurance_customers.avsc
 *     insurance_offers.avsc
 *     inventory.avsc
 *     map_dumb_schema.avsc
 *     net_device.avsc
 *     orders.avsc
 *     page_views.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizza_orders.avsc
 *     pizzaorderscancelled.avsc
 *     pizzaorderscompleted.avsc
 *     product.avsc
 *     purchase.avsc
 *     ratings.avsc
 *     shoe.avsc
 *     shoe_clickstream.avsc
 *     shoe_customer.avsc
 *     shoe_order.avsc
 *     siemlogs.avsc
 *     stock_trades.avsc
 *     stores.avsc
 *     sysloglogs.avsc
 *     transactions.avsc
 *     user.avsc
 *     users.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type CampaignFinance struct {
	Time int64 `json:"time"`

	Candidate_id string `json:"candidate_id"`

	Party_affiliation string `json:"party_affiliation"`

	Contribution int32 `json:"contribution"`
}

const CampaignFinanceAvroCRC64Fingerprint = "Ќ8\xa4\x80\x99\x1e\x10"

func NewCampaignFinance() CampaignFinance {
	r := CampaignFinance{}
	return r
}

func DeserializeCampaignFinance(r io.Reader) (CampaignFinance, error) {
	t := NewCampaignFinance()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeCampaignFinanceFromSchema(r io.Reader, schema string) (CampaignFinance, error) {
	t := NewCampaignFinance()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeCampaignFinance(r CampaignFinance, w io.Writer) error {
	var err error
	err = vm.WriteLong(r.Time, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Candidate_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Party_affiliation, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Contribution, w)
	if err != nil {
		return err
	}
	return err
}

func (r CampaignFinance) Serialize(w io.Writer) error {
	return writeCampaignFinance(r, w)
}

func (r CampaignFinance) Schema() string {
	return "{\"fields\":[{\"name\":\"time\",\"type\":{\"arg.properties\":{\"range\":{\"max\":1619273364600,\"min\":1587715775521}},\"type\":\"long\"}},{\"name\":\"candidate_id\",\"type\":{\"arg.properties\":{\"regex\":\"[A-Z][1-9]{8,8}\"},\"type\":\"string\"}},{\"name\":\"party_affiliation\",\"type\":{\"arg.properties\":{\"options\":[\"REP\",\"DEM\",\"IND\"]},\"type\":\"string\"}},{\"name\":\"contribution\",\"type\":{\"arg.properties\":{\"range\":{\"max\":3500,\"min\":20}},\"type\":\"int\"}}],\"name\":\"datagen.CampaignFinance\",\"type\":\"record\"}"
}

func (r CampaignFinance) SchemaName() string {
	return "datagen.CampaignFinance"
}

func (_ CampaignFinance) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ CampaignFinance) SetInt(v int32)       { panic("Unsupported operation") }
func (_ CampaignFinance) SetLong(v int64)      { panic("Unsupported operation") }
func (_ CampaignFinance) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ CampaignFinance) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ CampaignFinance) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ CampaignFinance) SetString(v string)   { panic("Unsupported operation") }
func (_ CampaignFinance) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *CampaignFinance) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Long{Target: &r.Time}

		return w

	case 1:
		w := types.String{Target: &r.Candidate_id}

		return w

	case 2:
		w := types.String{Target: &r.Party_affiliation}

		return w

	case 3:
		w := types.Int{Target: &r.Contribution}

		return w

	}
	panic("Unknown field index")
}

func (r *CampaignFinance) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *CampaignFinance) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ CampaignFinance) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ CampaignFinance) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ CampaignFinance) HintSize(int)                     { panic("Unsupported operation") }
func (_ CampaignFinance) Finalize()                        {}

func (_ CampaignFinance) AvroCRC64Fingerprint() []byte {
	return []byte(CampaignFinanceAvroCRC64Fingerprint)
}

func (r CampaignFinance) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["time"], err = json.Marshal(r.Time)
	if err != nil {
		return nil, err
	}
	output["candidate_id"], err = json.Marshal(r.Candidate_id)
	if err != nil {
		return nil, err
	}
	output["party_affiliation"], err = json.Marshal(r.Party_affiliation)
	if err != nil {
		return nil, err
	}
	output["contribution"], err = json.Marshal(r.Contribution)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *CampaignFinance) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["time"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Time); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for time")
	}
	val = func() json.RawMessage {
		if v, ok := fields["candidate_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Candidate_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for candidate_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["party_affiliation"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Party_affiliation); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for party_affiliation")
	}
	val = func() json.RawMessage {
		if v, ok := fields["contribution"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Contribution); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for contribution")
	}
	return nil
}
