// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type FleetmgmtSensor struct {
	Vehicle_id int32 `json:"vehicle_id"`

	Engine_temperature int32 `json:"engine_temperature"`

	Average_rpm int32 `json:"average_rpm"`
}

const FleetmgmtSensorAvroCRC64Fingerprint = "ī\x98\xf3\xe7n\xc9x"

func NewFleetmgmtSensor() FleetmgmtSensor {
	r := FleetmgmtSensor{}
	return r
}

func DeserializeFleetmgmtSensor(r io.Reader) (FleetmgmtSensor, error) {
	t := NewFleetmgmtSensor()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeFleetmgmtSensorFromSchema(r io.Reader, schema string) (FleetmgmtSensor, error) {
	t := NewFleetmgmtSensor()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeFleetmgmtSensor(r FleetmgmtSensor, w io.Writer) error {
	var err error
	err = vm.WriteInt(r.Vehicle_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Engine_temperature, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Average_rpm, w)
	if err != nil {
		return err
	}
	return err
}

func (r FleetmgmtSensor) Serialize(w io.Writer) error {
	return writeFleetmgmtSensor(r, w)
}

func (r FleetmgmtSensor) Schema() string {
	return "{\"fields\":[{\"name\":\"vehicle_id\",\"type\":{\"arg.properties\":{\"range\":{\"max\":9999,\"min\":1000}},\"type\":\"int\"}},{\"name\":\"engine_temperature\",\"type\":{\"arg.properties\":{\"range\":{\"max\":250,\"min\":150}},\"type\":\"int\"}},{\"name\":\"average_rpm\",\"type\":{\"arg.properties\":{\"range\":{\"max\":5000,\"min\":1800}},\"type\":\"int\"}}],\"name\":\"fleetmgmt.FleetmgmtSensor\",\"type\":\"record\"}"
}

func (r FleetmgmtSensor) SchemaName() string {
	return "fleetmgmt.FleetmgmtSensor"
}

func (_ FleetmgmtSensor) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetInt(v int32)       { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetLong(v int64)      { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetString(v string)   { panic("Unsupported operation") }
func (_ FleetmgmtSensor) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *FleetmgmtSensor) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Int{Target: &r.Vehicle_id}

		return w

	case 1:
		w := types.Int{Target: &r.Engine_temperature}

		return w

	case 2:
		w := types.Int{Target: &r.Average_rpm}

		return w

	}
	panic("Unknown field index")
}

func (r *FleetmgmtSensor) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *FleetmgmtSensor) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ FleetmgmtSensor) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ FleetmgmtSensor) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ FleetmgmtSensor) HintSize(int)                     { panic("Unsupported operation") }
func (_ FleetmgmtSensor) Finalize()                        {}

func (_ FleetmgmtSensor) AvroCRC64Fingerprint() []byte {
	return []byte(FleetmgmtSensorAvroCRC64Fingerprint)
}

func (r FleetmgmtSensor) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["vehicle_id"], err = json.Marshal(r.Vehicle_id)
	if err != nil {
		return nil, err
	}
	output["engine_temperature"], err = json.Marshal(r.Engine_temperature)
	if err != nil {
		return nil, err
	}
	output["average_rpm"], err = json.Marshal(r.Average_rpm)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *FleetmgmtSensor) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["vehicle_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Vehicle_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for vehicle_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["engine_temperature"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Engine_temperature); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for engine_temperature")
	}
	val = func() json.RawMessage {
		if v, ok := fields["average_rpm"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Average_rpm); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for average_rpm")
	}
	return nil
}
