// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type GamingGame struct {
	Id int32 `json:"id"`

	Room_name string `json:"room_name"`

	Created_date int64 `json:"created_date"`
}

const GamingGameAvroCRC64Fingerprint = "\xd7\xe57]\x1f\x8bTB"

func NewGamingGame() GamingGame {
	r := GamingGame{}
	return r
}

func DeserializeGamingGame(r io.Reader) (GamingGame, error) {
	t := NewGamingGame()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeGamingGameFromSchema(r io.Reader, schema string) (GamingGame, error) {
	t := NewGamingGame()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeGamingGame(r GamingGame, w io.Writer) error {
	var err error
	err = vm.WriteInt(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Room_name, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Created_date, w)
	if err != nil {
		return err
	}
	return err
}

func (r GamingGame) Serialize(w io.Writer) error {
	return writeGamingGame(r, w)
}

func (r GamingGame) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":{\"arg.properties\":{\"range\":{\"max\":5000,\"min\":1000}},\"type\":\"int\"}},{\"name\":\"room_name\",\"type\":{\"arg.properties\":{\"options\":[\"Arcade -- Rookie\",\"Arcade -- Skilled\",\"Arcade -- Expert\",\"Survival -- Rookie\",\"Survival -- Skilled\",\"Survival -- Expert\",\"Classic -- Rookie\",\"Classic -- Skilled\",\"Classic -- Expert\"]},\"type\":\"string\"}},{\"name\":\"created_date\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":1609459200000,\"step\":100000}},\"logicalType\":\"timestamp-millis\",\"type\":\"long\"}}],\"name\":\"gaming.GamingGame\",\"type\":\"record\"}"
}

func (r GamingGame) SchemaName() string {
	return "gaming.GamingGame"
}

func (_ GamingGame) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ GamingGame) SetInt(v int32)       { panic("Unsupported operation") }
func (_ GamingGame) SetLong(v int64)      { panic("Unsupported operation") }
func (_ GamingGame) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ GamingGame) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ GamingGame) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ GamingGame) SetString(v string)   { panic("Unsupported operation") }
func (_ GamingGame) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *GamingGame) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Int{Target: &r.Id}

		return w

	case 1:
		w := types.String{Target: &r.Room_name}

		return w

	case 2:
		w := types.Long{Target: &r.Created_date}

		return w

	}
	panic("Unknown field index")
}

func (r *GamingGame) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *GamingGame) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ GamingGame) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ GamingGame) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ GamingGame) HintSize(int)                     { panic("Unsupported operation") }
func (_ GamingGame) Finalize()                        {}

func (_ GamingGame) AvroCRC64Fingerprint() []byte {
	return []byte(GamingGameAvroCRC64Fingerprint)
}

func (r GamingGame) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["room_name"], err = json.Marshal(r.Room_name)
	if err != nil {
		return nil, err
	}
	output["created_date"], err = json.Marshal(r.Created_date)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *GamingGame) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["room_name"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Room_name); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for room_name")
	}
	val = func() json.RawMessage {
		if v, ok := fields["created_date"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Created_date); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for created_date")
	}
	return nil
}
