// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type InventorymgmtProduct struct {
	Id int64 `json:"id"`

	Name string `json:"name"`

	Description string `json:"description"`

	Price float64 `json:"price"`
}

const InventorymgmtProductAvroCRC64Fingerprint = "\x1a@Ə+۸i"

func NewInventorymgmtProduct() InventorymgmtProduct {
	r := InventorymgmtProduct{}
	return r
}

func DeserializeInventorymgmtProduct(r io.Reader) (InventorymgmtProduct, error) {
	t := NewInventorymgmtProduct()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeInventorymgmtProductFromSchema(r io.Reader, schema string) (InventorymgmtProduct, error) {
	t := NewInventorymgmtProduct()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeInventorymgmtProduct(r InventorymgmtProduct, w io.Writer) error {
	var err error
	err = vm.WriteLong(r.Id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Name, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Description, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.Price, w)
	if err != nil {
		return err
	}
	return err
}

func (r InventorymgmtProduct) Serialize(w io.Writer) error {
	return writeInventorymgmtProduct(r, w)
}

func (r InventorymgmtProduct) Schema() string {
	return "{\"fields\":[{\"name\":\"id\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":0}},\"type\":\"long\"}},{\"name\":\"name\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":0}},\"type\":\"string\"}},{\"name\":\"description\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":0}},\"type\":\"string\"}},{\"name\":\"price\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":0}},\"type\":\"double\"}}],\"name\":\"product.InventorymgmtProduct\",\"type\":\"record\"}"
}

func (r InventorymgmtProduct) SchemaName() string {
	return "product.InventorymgmtProduct"
}

func (_ InventorymgmtProduct) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetInt(v int32)       { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetLong(v int64)      { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetString(v string)   { panic("Unsupported operation") }
func (_ InventorymgmtProduct) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *InventorymgmtProduct) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Long{Target: &r.Id}

		return w

	case 1:
		w := types.String{Target: &r.Name}

		return w

	case 2:
		w := types.String{Target: &r.Description}

		return w

	case 3:
		w := types.Double{Target: &r.Price}

		return w

	}
	panic("Unknown field index")
}

func (r *InventorymgmtProduct) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *InventorymgmtProduct) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ InventorymgmtProduct) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ InventorymgmtProduct) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ InventorymgmtProduct) HintSize(int)                     { panic("Unsupported operation") }
func (_ InventorymgmtProduct) Finalize()                        {}

func (_ InventorymgmtProduct) AvroCRC64Fingerprint() []byte {
	return []byte(InventorymgmtProductAvroCRC64Fingerprint)
}

func (r InventorymgmtProduct) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["id"], err = json.Marshal(r.Id)
	if err != nil {
		return nil, err
	}
	output["name"], err = json.Marshal(r.Name)
	if err != nil {
		return nil, err
	}
	output["description"], err = json.Marshal(r.Description)
	if err != nil {
		return nil, err
	}
	output["price"], err = json.Marshal(r.Price)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *InventorymgmtProduct) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["name"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Name); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for name")
	}
	val = func() json.RawMessage {
		if v, ok := fields["description"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Description); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for description")
	}
	val = func() json.RawMessage {
		if v, ok := fields["price"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Price); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for price")
	}
	return nil
}
