// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type MarketingCampaignFinance struct {
	Time int64 `json:"time"`

	Candidate_id string `json:"candidate_id"`

	Party_affiliation string `json:"party_affiliation"`

	Contribution int32 `json:"contribution"`
}

const MarketingCampaignFinanceAvroCRC64Fingerprint = "d\x91d\xafv\xbc6\xe9"

func NewMarketingCampaignFinance() MarketingCampaignFinance {
	r := MarketingCampaignFinance{}
	return r
}

func DeserializeMarketingCampaignFinance(r io.Reader) (MarketingCampaignFinance, error) {
	t := NewMarketingCampaignFinance()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeMarketingCampaignFinanceFromSchema(r io.Reader, schema string) (MarketingCampaignFinance, error) {
	t := NewMarketingCampaignFinance()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeMarketingCampaignFinance(r MarketingCampaignFinance, w io.Writer) error {
	var err error
	err = vm.WriteLong(r.Time, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Candidate_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Party_affiliation, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Contribution, w)
	if err != nil {
		return err
	}
	return err
}

func (r MarketingCampaignFinance) Serialize(w io.Writer) error {
	return writeMarketingCampaignFinance(r, w)
}

func (r MarketingCampaignFinance) Schema() string {
	return "{\"fields\":[{\"name\":\"time\",\"type\":{\"arg.properties\":{\"range\":{\"max\":1619273364600,\"min\":1587715775521}},\"type\":\"long\"}},{\"name\":\"candidate_id\",\"type\":{\"arg.properties\":{\"regex\":\"[A-Z][1-9]{8,8}\"},\"type\":\"string\"}},{\"name\":\"party_affiliation\",\"type\":{\"arg.properties\":{\"options\":[\"REP\",\"DEM\",\"IND\"]},\"type\":\"string\"}},{\"name\":\"contribution\",\"type\":{\"arg.properties\":{\"range\":{\"max\":3500,\"min\":20}},\"type\":\"int\"}}],\"name\":\"marketing.MarketingCampaignFinance\",\"type\":\"record\"}"
}

func (r MarketingCampaignFinance) SchemaName() string {
	return "marketing.MarketingCampaignFinance"
}

func (_ MarketingCampaignFinance) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetInt(v int32)       { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetLong(v int64)      { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetString(v string)   { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *MarketingCampaignFinance) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Long{Target: &r.Time}

		return w

	case 1:
		w := types.String{Target: &r.Candidate_id}

		return w

	case 2:
		w := types.String{Target: &r.Party_affiliation}

		return w

	case 3:
		w := types.Int{Target: &r.Contribution}

		return w

	}
	panic("Unknown field index")
}

func (r *MarketingCampaignFinance) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *MarketingCampaignFinance) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ MarketingCampaignFinance) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) HintSize(int)                     { panic("Unsupported operation") }
func (_ MarketingCampaignFinance) Finalize()                        {}

func (_ MarketingCampaignFinance) AvroCRC64Fingerprint() []byte {
	return []byte(MarketingCampaignFinanceAvroCRC64Fingerprint)
}

func (r MarketingCampaignFinance) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["time"], err = json.Marshal(r.Time)
	if err != nil {
		return nil, err
	}
	output["candidate_id"], err = json.Marshal(r.Candidate_id)
	if err != nil {
		return nil, err
	}
	output["party_affiliation"], err = json.Marshal(r.Party_affiliation)
	if err != nil {
		return nil, err
	}
	output["contribution"], err = json.Marshal(r.Contribution)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *MarketingCampaignFinance) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["time"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Time); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for time")
	}
	val = func() json.RawMessage {
		if v, ok := fields["candidate_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Candidate_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for candidate_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["party_affiliation"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Party_affiliation); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for party_affiliation")
	}
	val = func() json.RawMessage {
		if v, ok := fields["contribution"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Contribution); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for contribution")
	}
	return nil
}
