// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type PaymentTransaction struct {
	Transaction_id int64 `json:"transaction_id"`

	Card_id int64 `json:"card_id"`

	User_id string `json:"user_id"`

	Purchase_id int64 `json:"purchase_id"`

	Store_id int32 `json:"store_id"`
}

const PaymentTransactionAvroCRC64Fingerprint = "\x1c\xf4\xf3^v\x9eU\xad"

func NewPaymentTransaction() PaymentTransaction {
	r := PaymentTransaction{}
	return r
}

func DeserializePaymentTransaction(r io.Reader) (PaymentTransaction, error) {
	t := NewPaymentTransaction()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializePaymentTransactionFromSchema(r io.Reader, schema string) (PaymentTransaction, error) {
	t := NewPaymentTransaction()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writePaymentTransaction(r PaymentTransaction, w io.Writer) error {
	var err error
	err = vm.WriteLong(r.Transaction_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Card_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.User_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Purchase_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteInt(r.Store_id, w)
	if err != nil {
		return err
	}
	return err
}

func (r PaymentTransaction) Serialize(w io.Writer) error {
	return writePaymentTransaction(r, w)
}

func (r PaymentTransaction) Schema() string {
	return "{\"fields\":[{\"name\":\"transaction_id\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":1}},\"type\":\"long\"}},{\"name\":\"card_id\",\"type\":{\"arg.properties\":{\"range\":{\"max\":24,\"min\":1}},\"type\":\"long\"}},{\"name\":\"user_id\",\"type\":{\"arg.properties\":{\"regex\":\"User_[1-9]{0,1}\"},\"type\":\"string\"}},{\"name\":\"purchase_id\",\"type\":{\"arg.properties\":{\"iteration\":{\"start\":0}},\"type\":\"long\"}},{\"name\":\"store_id\",\"type\":{\"arg.properties\":{\"range\":{\"max\":7,\"min\":1}},\"type\":\"int\"}}],\"name\":\"transaction.PaymentTransaction\",\"type\":\"record\"}"
}

func (r PaymentTransaction) SchemaName() string {
	return "transaction.PaymentTransaction"
}

func (_ PaymentTransaction) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ PaymentTransaction) SetInt(v int32)       { panic("Unsupported operation") }
func (_ PaymentTransaction) SetLong(v int64)      { panic("Unsupported operation") }
func (_ PaymentTransaction) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ PaymentTransaction) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ PaymentTransaction) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ PaymentTransaction) SetString(v string)   { panic("Unsupported operation") }
func (_ PaymentTransaction) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *PaymentTransaction) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Long{Target: &r.Transaction_id}

		return w

	case 1:
		w := types.Long{Target: &r.Card_id}

		return w

	case 2:
		w := types.String{Target: &r.User_id}

		return w

	case 3:
		w := types.Long{Target: &r.Purchase_id}

		return w

	case 4:
		w := types.Int{Target: &r.Store_id}

		return w

	}
	panic("Unknown field index")
}

func (r *PaymentTransaction) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *PaymentTransaction) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ PaymentTransaction) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ PaymentTransaction) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ PaymentTransaction) HintSize(int)                     { panic("Unsupported operation") }
func (_ PaymentTransaction) Finalize()                        {}

func (_ PaymentTransaction) AvroCRC64Fingerprint() []byte {
	return []byte(PaymentTransactionAvroCRC64Fingerprint)
}

func (r PaymentTransaction) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["transaction_id"], err = json.Marshal(r.Transaction_id)
	if err != nil {
		return nil, err
	}
	output["card_id"], err = json.Marshal(r.Card_id)
	if err != nil {
		return nil, err
	}
	output["user_id"], err = json.Marshal(r.User_id)
	if err != nil {
		return nil, err
	}
	output["purchase_id"], err = json.Marshal(r.Purchase_id)
	if err != nil {
		return nil, err
	}
	output["store_id"], err = json.Marshal(r.Store_id)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *PaymentTransaction) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["transaction_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Transaction_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for transaction_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["card_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Card_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for card_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["user_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.User_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for user_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["purchase_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Purchase_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for purchase_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["store_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Store_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for store_id")
	}
	return nil
}
