// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCES:
 *     csv_product.avsc
 *     csv_user.avsc
 *     finance_stock_trade.avsc
 *     fleetmgmt_description.avsc
 *     fleetmgmt_location.avsc
 *     fleetmgmt_sensor.avsc
 *     gaming_game.avsc
 *     gaming_player.avsc
 *     gaming_player_activity.avsc
 *     genericstore_purchase.avsc
 *     insurance_customer.avsc
 *     insurance_customer_activity.avsc
 *     insurance_offer.avsc
 *     inventorymgmt_inventory.avsc
 *     inventorymgmt_product.avsc
 *     iot_device_information.avsc
 *     map_dumb_schema.avsc
 *     marketing_campaign_finance.avsc
 *     net_device.avsc
 *     payment_credit_card.avsc
 *     payment_transaction.avsc
 *     payroll_bonus.avsc
 *     payroll_employee.avsc
 *     payroll_employee_location.avsc
 *     pizzastore_order.avsc
 *     pizzastore_order_cancelled.avsc
 *     pizzastore_order_completed.avsc
 *     shoestore_clickstream.avsc
 *     shoestore_customer.avsc
 *     shoestore_order.avsc
 *     shoestore_shoe.avsc
 *     shopping_order.avsc
 *     shopping_rating.avsc
 *     siem_log.avsc
 *     store.avsc
 *     syslog_log.avsc
 *     user.avsc
 *     users.avsc
 *     users_array_map.avsc
 *     webanalytics_clickstream.avsc
 *     webanalytics_code.avsc
 *     webanalytics_page_view.avsc
 *     webanalytics_user.avsc
 */
package types

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type WebanalyticsCode struct {
	Code int32 `json:"code"`

	Definition string `json:"definition"`
}

const WebanalyticsCodeAvroCRC64Fingerprint = "i\xce/\xb4\xc65\xa5."

func NewWebanalyticsCode() WebanalyticsCode {
	r := WebanalyticsCode{}
	return r
}

func DeserializeWebanalyticsCode(r io.Reader) (WebanalyticsCode, error) {
	t := NewWebanalyticsCode()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeWebanalyticsCodeFromSchema(r io.Reader, schema string) (WebanalyticsCode, error) {
	t := NewWebanalyticsCode()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeWebanalyticsCode(r WebanalyticsCode, w io.Writer) error {
	var err error
	err = vm.WriteInt(r.Code, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Definition, w)
	if err != nil {
		return err
	}
	return err
}

func (r WebanalyticsCode) Serialize(w io.Writer) error {
	return writeWebanalyticsCode(r, w)
}

func (r WebanalyticsCode) Schema() string {
	return "{\"arg.properties\":{\"options\":[{\"code\":200,\"definition\":\"Successful\"},{\"code\":302,\"definition\":\"Redirect\"},{\"code\":404,\"definition\":\"Page not found\"},{\"code\":405,\"definition\":\"Method not allowed\"},{\"code\":406,\"definition\":\"Not acceptable\"},{\"code\":407,\"definition\":\"Proxy authentication required\"}]},\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"definition\",\"type\":\"string\"}],\"name\":\"webanalytics.WebanalyticsCode\",\"type\":\"record\"}"
}

func (r WebanalyticsCode) SchemaName() string {
	return "webanalytics.WebanalyticsCode"
}

func (_ WebanalyticsCode) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetInt(v int32)       { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetLong(v int64)      { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetString(v string)   { panic("Unsupported operation") }
func (_ WebanalyticsCode) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *WebanalyticsCode) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.Int{Target: &r.Code}

		return w

	case 1:
		w := types.String{Target: &r.Definition}

		return w

	}
	panic("Unknown field index")
}

func (r *WebanalyticsCode) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *WebanalyticsCode) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ WebanalyticsCode) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ WebanalyticsCode) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ WebanalyticsCode) HintSize(int)                     { panic("Unsupported operation") }
func (_ WebanalyticsCode) Finalize()                        {}

func (_ WebanalyticsCode) AvroCRC64Fingerprint() []byte {
	return []byte(WebanalyticsCodeAvroCRC64Fingerprint)
}

func (r WebanalyticsCode) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["code"], err = json.Marshal(r.Code)
	if err != nil {
		return nil, err
	}
	output["definition"], err = json.Marshal(r.Definition)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *WebanalyticsCode) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["code"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Code); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for code")
	}
	val = func() json.RawMessage {
		if v, ok := fields["definition"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Definition); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for definition")
	}
	return nil
}
